Check losses

In [7]:
import os

os.environ['THEANO_FLAGS'] = 'device=cpu'

import numpy as np

In [11]:
from keras.losses import categorical_crossentropy, mae, mse, mape
from keras import backend as K

In [12]:
Y_true = K.placeholder(dtype=K.floatx(), shape=(None, 17))
Y_pred = K.placeholder(dtype=K.floatx(), shape=(None, 17))

In [13]:
Loss_1 = categorical_crossentropy(Y_true, Y_pred)
Loss_2 = mae(Y_true, Y_pred)
Loss_3 = mse(Y_true, Y_pred)
Loss_4 = mape(Y_true, Y_pred)

In [14]:
y_true = np.array([[0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0], ], dtype=np.float32)
y_pred = 0.5 * np.ones((1, 17), dtype=np.float32)
# y_pred = np.array([[0.5, 0.5, 0.5, 0.5,         0.5 ,        0.5  ,        0.5,  0.52489066,  1.   ,       0.5 ,        0.99995756 , 1.    ,      0.5   ,      0.5,  0.5  ,       0.51348531,  0.5       ], ], dtype=np.float32)

# -- ('8653', 'Train_jpg')
# y_true:  [0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0]
# y_pred:  [ 0.5         0.5         0.5         0.5         0.5         0.99998951
#   0.5         0.5         0.50315326  0.99999619  0.5         0.5
#   0.74787986  0.5         0.5         0.5         0.5       ]

In [15]:
Loss_1.eval(inputs_to_values={Y_true: y_true, Y_pred: y_pred})

array([ 8.49963951], dtype=float32)

In [16]:
Loss_2.eval(inputs_to_values={Y_true: y_true, Y_pred: y_pred})

array([ 0.5], dtype=float32)

In [17]:
Loss_3.eval(inputs_to_values={Y_true: y_true, Y_pred: y_pred})

array([ 0.25], dtype=float32)

In [18]:
Loss_4.eval(inputs_to_values={Y_true: y_true, Y_pred: y_pred})

array([  4.11764704e+08], dtype=float32)

In [6]:
15 * 15 * 17 * 96

367200